/*
===============================================================================
Part to whole Analysis
===============================================================================

Purpose:
    - Analyze total sales generated by each country.
    - Determine each country's contribution to overall sales performance.
*/

-- Which countries contribute the most to overall sales

with country_sales as
(
select 
		
		c.country,
		SUM(sales) as total_sales
from gold.fact_sales as s
left join gold.dim_customers as c
on s.customer_key = c.customer_key 
group by c.country
)
    select 
    	country,
    	total_sales,
    	SUM(total_sales) over () as overall_sales,
    	CONCAT(ROUND(CAST(total_sales as float) / SUM(total_sales) over () * 100,2),'%') as perc_of_total
    from country_sales
    order by total_sales desc
