/*
===============================================================================
Part to whole Analysis
===============================================================================

Purpose:
    - Analyze total sales generated by each country.
    - Determine each country's contribution to overall sales performance.
    - Analyze total orders generated by each gender.
	- Determine each genders contribution to overall orders .
*/


                                        -- Which countries contribute the most to overall sales

with country_sales as
(
select 
		
		c.country,
		SUM(sales) as total_sales
from gold.fact_sales as s
left join gold.dim_customers as c
on s.customer_key = c.customer_key 
group by c.country
)
    select 
    	country,
    	total_sales,
    	SUM(total_sales) over () as overall_sales,
    	CONCAT(ROUND(CAST(total_sales as float) / SUM(total_sales) over () * 100,2),'%') as perc_of_total
    from country_sales
    order by total_sales desc

	
                                       -- Which gender contributes the most to overall orders

with orders_by_gender as
(
select 
		
		c.gender,
		COUNT(order_number) as total_orders
from gold.fact_sales as s
left join gold.dim_customers as c
on s.customer_key = c.customer_key 
group by c.gender
)
		select 
				gender,
				total_orders,
				SUM(total_orders) over() as overall_orders,
				CONCAT(ROUND(CAST(total_orders as float)/SUM(total_orders) over() * 100,2),'%') as percetage_orders_by_gen
		from orders_by_gender
		order by total_orders desc

